version: 1
smoothing:
  position_ms: 120
  movement_ms: 120
  curvature_ms: 80
  gesture_ms: 80
calibration:
  right_hand.motion.up:
    axis:
    - 0.0
    - -1.0
    range_norm: -200 # this is the right hand motion up calibration
  right_hand.motion.left:
    axis:
    - 1.0
    - 0.0
    range_norm: -300 # this is the right hand motion left calibration
  right_hand.pos:
    quad:
    - [0, 0]
    - [1, 0]
    - [1, 1]
    - [0, 1]
  right_hand.gesture.closed:
    min: 0.5
    max: 1.2
bindings:
- id: move_x
  actuator: mouse.move.x
  input: right_hand.motion.left
  sensitivity: 1920.0
  deadzone: 0.001
  gate:
    input: right_hand.gesture.closed
    op: '<'
    trigger_pct: 0.5
    release_pct: 0.45
    refractory_ms: 120
    lost_hand_policy: release
  lost_hand_policy: zero
  debug:
  - feature
  - gate
  - actuator
- id: move_y
  actuator: mouse.move.y
  input: right_hand.motion.up
  sensitivity: -1080.0
  deadzone: 0.001
  gate:
    input: right_hand.gesture.closed
    op: '<'
    trigger_pct: 0.5
    release_pct: 0.45
    refractory_ms: 120
    lost_hand_policy: release
  lost_hand_policy: zero
  debug:
  - feature
  - gate
  - actuator
last_camera:
  backend: any
  name: ''
  id: ''
  index: 0
